### PR TITLE
correct style guide errors and make files more readable

### PR DESCRIPTION
**Pull request by icsvortex666**
Please take a look at all of the changes.

### CODE REVIEW

**Comment by tmulroy** [comment]
It doesn't seem to read well with me, for example, when you break down [key, value] into:  
[
key,
value
]
in the DAOs, it adds lines and makes it harder to read

**Comment by icsvortex666** [comment]
I'll fix that for you

**Comment by tmulroy** [comment]
Thanks, here's an example of what I mean:
screenshot from 2016-10-12 16-55-11

**Comment by icsvortex666** [comment]
@tmulroy go check it

**Comment by markrivasrobertson** [comment]
yeah I feel like putting the arguments for constructors on individual lines that had been on one line isn't really adding much to readability since the those arguments are assigned just a moment later to properties each on separate lines

**Comment by icsvortex666** [comment]
I understand it for lines like 
```
.one(sql.find, [key, value])
```
But for longer lines like
```
constructor({
    id,
    body,
    user_id,
    project_id,
    created,
  }) {
    this.id = id;
    this.body = body;
    this.user_id = user_id;
    this.project_id = project_id;
    this.created = created;
  }
```
it's better that way

**Comment by icsvortex666** [comment]
Feel free to change the lines if they bother you, code is communication. I only change the lines that feel really messy and hard to read when they are cluttered with code.

**Pull request merged**
